SETTINGS_PREFIX := $(SRCS_PATH)settings/

INCLUDES += -I$(SETTINGS_PREFIX) \
            -I$(SETTINGS_PREFIX)modbus_settings/ \
			-I$(SETTINGS_PREFIX)reporting_intervals/

SRCS += $(SETTINGS_PREFIX)settings.c \
        $(SETTINGS_PREFIX)modbus_settings/modbus_settings.c \
		$(SETTINGS_PREFIX)reporting_intervals/reporting_intervals.c